server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}

stat-server:
  url: ${STATS_SERVER_URL:http://localhost:9090}
