version: '3.1'
services:
  stats-server:
    build: stats/stat-server
    image: stats-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_pass

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_pass

  ewm-service:
    build: ewm-service/
    image: ewm-service-image
    container_name: ewm-service-container
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_pass
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_pass
